# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63c0a485a5ea24015b1be34fb8a3e9520da61ad06a1dee312ceba38f44fd4c33574bd4c4e79e98f472ba5ca7b67fbab489aab7d0a8b3b70160b8459a31514f12

test:
  secret_key_base: 907463717a276bfb5d4613f8ae5762f6984f56b1d70db535f58587afab511d0627152212cf49396b0c28e3fa1f1a61a450b5770b25dce84fa6f913a0d1401c9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
